name: flutter_web_desktop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  native_pdf_view: ^4.1.0
  painter: ^2.0.0
  flutter_colorpicker: ^1.0.3
  screenshot: ^1.2.3
  assets_audio_player: ^3.0.4+1
  flutter_simple_calculator: ^2.0.0+1
  reorderables: ^0.4.2
  video_player: ^2.2.18
  flutter_treeview: ^1.0.7+1
  photo_view: ^0.12.0
  maze: ^3.0.0
  flutter_widget_from_html_core: ^0.8.4
  url_launcher: ^6.0.18
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/photos/
    - assets/photos/memes/
    - assets/photos/game/
    - assets/photos/instagram/
    - assets/images/
    - assets/icons/
    - assets/mazeResources/
    - assets/thumbnails/
    - assets/pdf/
    - assets/html/
    - assets/erro.mp3
  uses-material-design: true

